# Generated by Django 5.2.7 on 2026-01-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cart_id_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
