# Generated by Django 5.2.7 on 2026-01-09 16:59

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_review_confidence_review_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images/products', validators=[store.validators.validate_file_size]),
        ),
    ]
