# Generated by Django 5.2.7 on 2026-01-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
